services:
  configurator:
    environment:
      PROJECT_CLONE_URL: https://github.com/ajeetraina/labspace-cagent

  mcp-gateway:
    image: docker/mcp-gateway
    container_name: labspace-mcp-gateway
    command:
      - --port=8080
      - --transport=sse
      - --servers=fetch,duckduckgo,context7
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
